version: 1.1.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore -verbosity detailed
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: StatsdClient.*.nupkg
  name: NuGet Package
cache:
- packages -> **\packages.config
